ALTER TABLE payments
    MODIFY COLUMN status ENUM ('READY', 'PROCESSING', 'SUCCESS', 'DECLINED', 'FAILED', 'UNKNOWN', 'CANCELED', 'REFUNDED') NOT NULL;

UPDATE payments
SET status = 'DECLINED'
WHERE status = 'FAILED';

ALTER TABLE payments
    MODIFY COLUMN status ENUM ('READY', 'PROCESSING', 'SUCCESS', 'DECLINED', 'UNKNOWN', 'CANCELED', 'REFUNDED') NOT NULL;

ALTER TABLE payment_attempts
    MODIFY COLUMN status ENUM ('REQUESTED', 'SUCCESS', 'DECLINED', 'FAILED', 'PROVIDER_ERROR', 'TIMEOUT', 'UNKNOWN') NOT NULL;

UPDATE payment_attempts
SET status = 'DECLINED'
WHERE status = 'FAILED';

ALTER TABLE payment_attempts
    MODIFY COLUMN status ENUM ('REQUESTED', 'SUCCESS', 'DECLINED', 'PROVIDER_ERROR', 'TIMEOUT', 'UNKNOWN') NOT NULL;
